views:

  testView:  
    route: /test
    method: GET
    urn: file:test.php

  getLcoBalance:
    route: /lco/balance/@lcocode
    method: GET
    urn: file:lco/get_balance.php

  getLcoBalance:
    route: /lco/lcobyvcno/@vcno
    method: GET
    urn: file:lco/get_lco_obj_byvcno.php


  getSP:
    route: /lco/basetarifrenew
    method: POST
    urn: file:lco/exe_prepaid_base_tarif.php

  getCalculator:
    route: /lco/calculateTarif
    method: POST
    urn: file:lco/exe_prepaid_price_calculator.php


configuration:
  mssql:
    servername: 172.16.8.54
    parameters:
      UID: sa
      PWD: p@ssw0rd
      Database: dendb