views:

  testView:  
    route: /version
    method: GET
    urn: file:test.php

  getLcoBalance:
    route: /lco/balance/@lcocode
    method: GET
    urn: file:lco/get_balance.php

  getLcovcno:
    route: /lco/lcobyvcno/@vcno
    method: GET
    urn: file:lco/get_lco_obj_byvcno.php

  getAccount:
    route: /account/byvc/@vcno
    method: GET
    urn: file:account/account.php

  getAccountRenew:
    route: /account/renewcalculator/@packagetype/@vcno
    method: GET
    urn: file:account/renew_v1.php

  getSP:
    route: /lco/basetarifrenew
    method: POST
    urn: file:lco/exe_prepaid_base_tarif.php

  getCalculator:
    route: /lco/calculateTarif
    method: POST
    urn: file:lco/exe_prepaid_price_calculator.php

  get_rpt_exp_accounts:
    route: /lco/renew_expiringaccounts/@lcocode/@lastid/@days
    method: GET
    urn: file:lco/rpt_lcorenew.php

  get_rpt_lco_accounts:
    route: /lco/renewboxes/@lcocode/@lastid
    method: GET
    urn: file:lco/rpt_lcoboxes.php
  
  get_rpt_lco_accounts_v1:
    route: /lco/accounts_v1/@gulcoid/@cache/@page
    method: GET
    urn: file:lco/rpt_lcoboxes_v1.php

  get_rpt_lco_accounts_v1_cache:
    route: /lco/accounts_v1/cache/@gulcoid/@page
    method: GET
    urn: file:lco/rpt_lcoboxes_v1_cacheupdate.php


  get_lco_calculation_csv:
    route: /lco/files/calculation/@lcoid
    method: GET
    urn: file:files/lco_renew_recharge.php


configuration:
  mssql:
    servername: 172.16.8.54
    parameters:
      UID: sa
      PWD: p@ssw0rd
      Database: dendb